# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3-seleniumgrid.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3-seleniumgrid.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
  #      - SE_NODE_SESSION_TIMEOUT=180

#  SE_NODE_MAX_INSTANCES: This defines how many instances of same version of browser can run over the Remote System.
#  SE_NODE_MAX_SESSIONS: This defines maximum number of concurrent sessions that will be allowed.

#  edge:
#    image: selenium/node-edge:4.1.4-20220427
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_INSTANCES=1
#      - SE_NODE_MAX_SESSIONS=1
#  #      - SE_NODE_SESSION_TIMEOUT=180
#
#  firefox:
#    image: selenium/node-firefox:4.1.4-20220427
#    shm_size: 2gb
#    depends_on:
#      - selenium-hub
#    environment:
#      - SE_EVENT_BUS_HOST=selenium-hub
#      - SE_EVENT_BUS_PUBLISH_PORT=4442
#      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#      - SE_NODE_MAX_INSTANCES=1
#      - SE_NODE_MAX_SESSIONS=1
#  #      - SE_NODE_SESSION_TIMEOUT=180

  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


### To start the grid
# docker compose -f docker-compose-v3-seleniumgrid.yml up
### if we want to scale up the chrome service
# docker compose -f docker-compose-v3-seleniumgrid.yml up --scale chrome=5

### Once the grid is up and running, we can navigate to http://localhost:4444

### if you get error like - "The container name "/selenium-hub" is already in use by container..." the run below cmd
### to get all containers list and remove existing or rename
# docker ps -a
# docker rm <container-name> or docker container rename <CONTAINER> <NEW_NAME>

### In Grid you can navigate to sessions and click on video option to see the run visually and enter "secret" as password if asked

### To restart the container, selenium-hub
# docker compose -f docker-compose-v3-seleniumgrid.yml restart selenium-hub

### To stop the grid
# docker compose -f docker-compose-v3-seleniumgrid.yml down

### To restart the grid,
# docker compose -f docker-compose-v3-seleniumgrid.yml up

### For reference
# https://medium.com/@iamfaisalkhatri/parallel-execution-of-tests-using-selenium-grid-4-with-docker-compose-2dc243f4fe8b


#  docker compose -f docker-compose-v3-seleniumgrid.yml up --build && docker compose -f docker-compose-v3-seleniumgrid.yml restart selenium-hub

